// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SkyMapper.DataAccess;

#nullable disable

namespace SkyMapper.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.15");

            modelBuilder.Entity("SkyMapper.DataAccess.Models.Exclusions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Exclusions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Pattern = "textures\\\\lod\\\\"
                        },
                        new
                        {
                            Id = 2,
                            Pattern = "textures\\\\interface\\\\"
                        },
                        new
                        {
                            Id = 3,
                            Pattern = "textures\\\\DynDOLOD\\\\"
                        },
                        new
                        {
                            Id = 4,
                            Pattern = "textures\\\\terrain\\\\"
                        },
                        new
                        {
                            Id = 5,
                            Pattern = "textures\\\\.*\\\\chargen\\\\"
                        },
                        new
                        {
                            Id = 6,
                            Pattern = "textures\\\\.*\\\\cubemap.*\\\\"
                        },
                        new
                        {
                            Id = 7,
                            Pattern = "textures\\\\.*\\\\facegen.*\\\\"
                        },
                        new
                        {
                            Id = 8,
                            Pattern = "textures\\\\.*\\\\*hair.*\\\\"
                        },
                        new
                        {
                            Id = 9,
                            Pattern = "textures\\\\.*\\\\*brow.*\\\\"
                        },
                        new
                        {
                            Id = 10,
                            Pattern = "textures\\\\.*\\\\mouth\\\\"
                        },
                        new
                        {
                            Id = 11,
                            Pattern = "textures\\\\.*\\\\*eyes\\\\"
                        },
                        new
                        {
                            Id = 12,
                            Pattern = "textures\\\\.*\\\\*beard.*\\\\"
                        },
                        new
                        {
                            Id = 13,
                            Pattern = "textures\\\\.*\\\\*lashes\\\\"
                        },
                        new
                        {
                            Id = 14,
                            Pattern = "textures\\\\.*\\\\*gash\\\\"
                        },
                        new
                        {
                            Id = 15,
                            Pattern = "textures\\\\.*\\\\*tattoo\\\\"
                        },
                        new
                        {
                            Id = 16,
                            Pattern = "textures\\\\.*\\\\*skin.*\\\\"
                        });
                });

            modelBuilder.Entity("SkyMapper.DataAccess.Models.Settings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("GameDataFolderLocation")
                        .HasColumnType("varchar(500)");

                    b.Property<int>("HeightMapIntensity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HeightMapMaxSteps")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HeightMapPasses")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxThreads")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ReprocessFailedTextures")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SyncOutputFolder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("SkyMapper.DataAccess.Models.TextureFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FailureError")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FileHashMd5")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsFailed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TextureFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
